### ISSUE TITLE
How to update this plugin

### ISSUE THREAD

**Issue by Windayz** [LibreCodeCoop/trademark#6]
Hello,

I've downloaded the new release, deleted the old plugin folder and added the new one, but GLPI doesn't suggest that I update.
What should I do?

Thanks

**Comment by Windayz** [comment]
You forgot to modify setup.php with the correct version number:

<?php
define('PLUGIN_TRADEMARK_VERSION', '1.3.0'); -> 1.4.0
// Minimal GLPI version, inclusive
define("PLUGIN_TRADEMARK_MIN_GLPI_VERSION", "10.0.0");

**Comment by vitormattos** [comment]
Thanks by your repport!

**Comment by vitormattos** [comment]
@Windayz could you check if the new release is ok?

**Comment by Windayz** [comment]
Yes, everything is ok, thank you :)

**Comment by vitormattos** [comment]
If you liked this app and others solutions of LibreCode, like [LibreSign](https://github.com/libresing/libresign), fell free to help us to maintain this and other open source softwares making a pontual or recurrent funding here:
https://github.com/sponsors/LibreSign
We centralized all sponsors at LibreSign project because is our main product now and we wish to have the enouth to be possible dedicate more time to open source projects and help other software engineers.
You also can help us making more tests, sending issues, giving stars at this repository and at LibreSign repository, announcing the LibreSign app and by a lot of other ways.
Very happy by your contribution!
Thanks a lot again!
